name: dockerhub-pushing

on:
  push:
    branches: [ "release" ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses: actions/checkout@v3
    
            
      - name: ls
        run:  ls
        
      
      - name: Build the phpmyadmin image
        run:  |
              cd phpMyAdmin
              docker build -t aliapovatijpes/lesson5:phpmyadmin-latest -t aliapovatijpes/lesson5:phpmyadmin-v1 .
              cd ..
      
      - name: Build the phpmyadmin image
        run:  |
              cd mysql
               pwd
               ls
         #     docker build -t aliapovatijpes/lesson5:phpmyadmin-latest -t aliapovatijpes/lesson5:phpmyadmin-v1 .
                    
          
      - name: Push the image to dockerhub
        run:  docker image push --all-tags aliapovatijpes/lesson5
 
