name: dockerhub-pushing

on:
  push:
    branches: [ "release" ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses: actions/checkout@v3
     
      - name: login to dockerhub
        run:  docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
     
      - name: Build the phpmyadmin image
        run:  |
              cd phpMyAdmin
              docker build -t aliapovatijpes/phpmyadmin:$GITHUB_RUN_NUMBER -t aliapovatijpes/phpmyadmin .
              cd ..
      
      - name: Build the mysql image
        run:  |
              cd mysql
              docker build -t aliapovatijpes/mysql:$GITHUB_RUN_NUMBER -t aliapovatijpes/mysql .
              
      - name: push all images to dockerhub
        run:  |
              docker image push --all-tags aliapovatijpes/phpmyadmin       
              docker image push --all-tags aliapovatijpes/mysql
