name: dockerhub-pushing

on:
  push:
    branches: [ "release" ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses: actions/checkout@v3
     
      - name: login to dockerhub
        run:  docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
     
      - name: Build the phpmyadmin image
        run:  |
              cd phpMyAdmin
              docker build -t aliapovatijpes/lesson5:phpmyadmin-v${{ GITHUB_RUN_NUMBER }} -t aliapovatijpes/lesson5:phpmyadmin-latest .
              cd ..
      
      - name: Build the mysql image
        run:  |
              cd mysql
              docker build -t aliapovatijpes/lesson5:mysql-v${{ GITHUB_RUN_NUMBER }} -t aliapovatijpes/lesson5:mysql-latest .
                    
          
      - name: Push images to dockerhub
        run:  docker image push --all-tags aliapovatijpes/lesson5
 
